[package]
name = "debilek-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
poise = "0.6.1"
songbird = { version = "0.5.0", default-features = true }
symphonia = { version = "0.5.0", features = ["aac", "mp3", "isomp4", "alac"] }
tokio = { version = "1.45.1", features = ["full"] }
reqwest = { version = "0.12.19", features = ["blocking"] }
once_cell = "1.19"
rand = "0.9.1"
dotenv = "0.15"
opentelemetry = "0.30.0"

[[bin]]
name = "debilek-bot"
path = "src/main.rs"