name: Build and Push ARM64 Docker Image

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: debilek-bot
  TARGET: aarch64-unknown-linux-gnu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build binary with Cross + cache
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: aarch64-unknown-linux-gnu
          args: "--locked --release"
          strip: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Make .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          envkey_TTS_KEY: ${{ secrets.TTS_KEY }}
          envkey_TTS_URL: ${{ vars.TTS_URL }}
          envkey_CONFIG: ${{ vars.CONFIG }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          platforms: linux/arm64
          file: Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/debilek-bot:latest