name: Build and Deploy Docker

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate .env File
        if: github.event_name == 'push'
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
          echo "TTS_KEY=${{ secrets.TTS_KEY }}" >> .env
          echo "TTS_URL=${{ vars.TTS_KEY }}" >> .env
          echo "CONFIG=${{ vars.TTS_KEY }}" >> .env

      - name: Build Docker Image (PR or Push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/debilek-bot:latest
          platforms: linux/arm64
